### ISSUE TITLE
Working on the current execution environment?

### ISSUE THREAD

**Issue by zol** [navihtot/node-canvas-aws-lambda#2]
I was wondering if you've managed to get canvas working on the current exec environment, `amzn-ami-hvm-2016.03.3.x86_64-gp2` (http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html)

**Comment by navihtot** [comment]
yes, it is working in production for me. with node version v4.3, don't know 6.10 though

**Comment by zol** [comment]
Thank you.

**Comment by alexandresaiz** [comment]
@navihtot do you plan to update this repo?

**Comment by navihtot** [comment]
Hey, unfortunately, no. For my use case, I stopped using caman and canvas for image filtering and opted out for using jimp (https://www.npmjs.com/package/jimp) as in that way I don't need any more precompiled dependencies. With precompiled dependencies, things were getting more and more complicated as my Lambda package grew over permitted size.
If it's possible for you, I strongly suggest avoiding dependencies that are not supported directly on lambda, it will make your life easier.

There is also sharp, very promising and performant image processing lib in node.js - https://github.com/lovell/sharp, from what the docs say it should be able to run on AWS Lambda

**Comment by navihtot** [comment]
@alexandresaiz If you really need this, you can follow how to: https://github.com/navihtot/node-caman-aws-lambda/blob/master/how-to.md
that should get you on your way to compile dependencies on your own
